version: '3.9'
services:
  moodist:
    image: ghcr.io/remvze/moodist
    logging:
      options:
        max-size: 1g
    restart: always
    ports:
      - '8080:8080'
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
